version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: energy-db
    ports:
      - "5433:5433"


volumes:
  db:
