version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_web
    command: python3 backend/src/access_service/bootstrap/entrypoint/fast_api.py
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - db

  bot:
    build:
      context: .
      dockerfile: Dockerfile_bot
    command: python3 bot/main.py
    env_file:
      - bot/.env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: energy-db
    ports:
      - "5433:5432"  # Левый — внешний порт, правый — внутренний
